parameters:
#    tperroin_tremplin_foyer.example.class: Tperroin\TremplinFoyerBundle\Example

services:
#    tperroin_tremplin_foyer.example:
#        class: %tperroin_tremplin_foyer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tperroin_tremplin_foyer.association:
        class: Tperroin\TremplinFoyerBundle\Admin\AssociationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foyer, label: Posts menu "Association" }
        arguments: [null, Tperroin\TremplinFoyerBundle\Entity\Association, TperroinTremplinFoyerBundle:AssociationAdmin]
    tperroin_tremplin_foyer.tremplin:
        class: Tperroin\TremplinFoyerBundle\Admin\AssociationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foyer, label: Posts menu "Tremplin" }
        arguments: [null, Tperroin\TremplinFoyerBundle\Entity\Tremplin, TperroinTremplinFoyerBundle:TremplinAdmin]