parameters:
#    tperroin_tremplin_foyer.example.class: Tperroin\TremplinFoyerBundle\Example

services:
#    tperroin_tremplin_foyer.example:
#        class: %tperroin_tremplin_foyer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tperroin_tremplin_foyer.association:
        class: Tperroin\TremplinFoyerBundle\Admin\AssociationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foyer, label: Posts menu "Association" }
        arguments: [null, Tperroin\TremplinFoyerBundle\Entity\Association, TperroinTremplinFoyerBundle:AssociationAdmin]
    tperroin_tremplin_foyer.tremplin:
        class: Tperroin\TremplinFoyerBundle\Admin\TremplinAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foyer, label: Posts menu "Tremplin" }
        arguments: [null, Tperroin\TremplinFoyerBundle\Entity\Tremplin, TperroinTremplinFoyerBundle:TremplinAdmin]
    tperroin_tremplin_foyer.groupe:
        class: Tperroin\TremplinFoyerBundle\Admin\GroupeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foyer, label: Posts menu "Groupe" }
        arguments: [null, Tperroin\TremplinFoyerBundle\Entity\Groupe, TperroinTremplinFoyerBundle:GroupeAdmin]
    tperroin_tremplin_foyer.partenaire:
        class: Tperroin\TremplinFoyerBundle\Admin\PartenaireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Foyer, label: Ajouter un partenaire }
        arguments: [null, Tperroin\TremplinFoyerBundle\Entity\Partenaire, TperroinTremplinFoyerBundle:PartenaireAdmin]
        
    tperroin.socialBarHelper:
        class : Tperroin\TremplinFoyerBundle\Templating\Helper\SocialBarHelper
        tags :
            - { name : 'templating.helper', alias : 'social-buttons' }
        arguments : [ @templating ]

    twig.extension.tperroin_social_bar:
        class: Tperroin\TremplinFoyerBundle\Twig\Extensions\TperroinTwigSocialBar
        tags:
            - { name: 'twig.extension' }
        arguments : [ @service_container ]