parameters:
#    tperroin_tremplin_foyer.example.class: Tperroin\TremplinFoyerBundle\Example

services:
#    tperroin_tremplin_foyer.example:
#        class: %tperroin_tremplin_foyer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
