<?php

namespace Tperroin\TremplinFoyerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TremplinController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Tperroin\TremplinFoyerBundle\Controller\TremplinController();
        return $instance;
    }
}
